namespace QuanLyQuanCafe_WF
{
    partial class FormThongKe
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            grpNgay = new GroupBox();
            lblChonNgay = new Label();
            dtpNgay = new DateTimePicker();
            btnTheoNgay = new Button();
            grpThang = new GroupBox();
            lblThangTitle = new Label();
            nudThang = new NumericUpDown();
            lblNamThangTitle = new Label();
            nudNam1 = new NumericUpDown();
            btnTheoThang = new Button();
            grpQuy = new GroupBox();
            lblQuyTitle = new Label();
            nudQuy = new NumericUpDown();
            lblNamQuyTitle = new Label();
            nudNam2 = new NumericUpDown();
            btnTheoQuy = new Button();
            grpNam = new GroupBox();
            lblNamTitle = new Label();
            nudNam3 = new NumericUpDown();
            btnTheoNam = new Button();
            lblKetQua = new Label();
            grpTop5 = new GroupBox();
            lblKieuTop5 = new Label();
            cboKieuTop5 = new ComboBox();
            dtpTop5 = new DateTimePicker();
            btnTop5 = new Button();
            lstTop5 = new ListBox();
            grpNgay.SuspendLayout();
            grpThang.SuspendLayout();
            grpQuy.SuspendLayout();
            grpNam.SuspendLayout();
            grpTop5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)nudThang).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudNam1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudQuy).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudNam2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudNam3).BeginInit();
            SuspendLayout();
            grpNgay.Font = new Font("Segoe UI", 9F);
            grpNgay.Location = new Point(20, 20);
            grpNgay.Name = "grpNgay";
            grpNgay.Size = new Size(280, 90);
            grpNgay.Text = "Doanh thu theo ngay";
            grpNgay.Controls.Add(lblChonNgay);
            grpNgay.Controls.Add(dtpNgay);
            grpNgay.Controls.Add(btnTheoNgay);
            lblChonNgay.Font = new Font("Segoe UI", 9F);
            lblChonNgay.Location = new Point(15, 30);
            lblChonNgay.Name = "lblChonNgay";
            lblChonNgay.Text = "Chon ngay:";
            lblChonNgay.AutoSize = true;
            dtpNgay.Format = DateTimePickerFormat.Short;
            dtpNgay.Location = new Point(15, 52);
            dtpNgay.Name = "dtpNgay";
            dtpNgay.Size = new Size(140, 25);
            btnTheoNgay.BackColor = Color.FromArgb(52, 152, 219);
            btnTheoNgay.FlatStyle = FlatStyle.Flat;
            btnTheoNgay.FlatAppearance.BorderSize = 0;
            btnTheoNgay.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnTheoNgay.ForeColor = Color.White;
            btnTheoNgay.Location = new Point(165, 50);
            btnTheoNgay.Name = "btnTheoNgay";
            btnTheoNgay.Size = new Size(100, 29);
            btnTheoNgay.Text = "XEM";
            btnTheoNgay.UseVisualStyleBackColor = false;
            btnTheoNgay.Click += btnTheoNgay_Click;
            grpThang.Font = new Font("Segoe UI", 9F);
            grpThang.Location = new Point(320, 20);
            grpThang.Name = "grpThang";
            grpThang.Size = new Size(280, 90);
            grpThang.Text = "Doanh thu theo thang";
            grpThang.Controls.Add(lblThangTitle);
            grpThang.Controls.Add(nudThang);
            grpThang.Controls.Add(lblNamThangTitle);
            grpThang.Controls.Add(nudNam1);
            grpThang.Controls.Add(btnTheoThang);
            lblThangTitle.Font = new Font("Segoe UI", 9F);
            lblThangTitle.Location = new Point(15, 30);
            lblThangTitle.Name = "lblThangTitle";
            lblThangTitle.Text = "Thang:";
            lblThangTitle.AutoSize = true;
            nudThang.Location = new Point(15, 52);
            nudThang.Maximum = new decimal(new int[] { 12, 0, 0, 0 });
            nudThang.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            nudThang.Name = "nudThang";
            nudThang.Size = new Size(50, 25);
            nudThang.Value = new decimal(new int[] { 1, 0, 0, 0 });
            lblNamThangTitle.Font = new Font("Segoe UI", 9F);
            lblNamThangTitle.Location = new Point(80, 30);
            lblNamThangTitle.Name = "lblNamThangTitle";
            lblNamThangTitle.Text = "Nam:";
            lblNamThangTitle.AutoSize = true;
            nudNam1.Location = new Point(80, 52);
            nudNam1.Maximum = new decimal(new int[] { 2100, 0, 0, 0 });
            nudNam1.Minimum = new decimal(new int[] { 2000, 0, 0, 0 });
            nudNam1.Name = "nudNam1";
            nudNam1.Size = new Size(70, 25);
            nudNam1.Value = new decimal(new int[] { 2026, 0, 0, 0 });
            btnTheoThang.BackColor = Color.FromArgb(52, 152, 219);
            btnTheoThang.FlatStyle = FlatStyle.Flat;
            btnTheoThang.FlatAppearance.BorderSize = 0;
            btnTheoThang.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnTheoThang.ForeColor = Color.White;
            btnTheoThang.Location = new Point(165, 50);
            btnTheoThang.Name = "btnTheoThang";
            btnTheoThang.Size = new Size(100, 29);
            btnTheoThang.Text = "XEM";
            btnTheoThang.UseVisualStyleBackColor = false;
            btnTheoThang.Click += btnTheoThang_Click;
            grpQuy.Font = new Font("Segoe UI", 9F);
            grpQuy.Location = new Point(620, 20);
            grpQuy.Name = "grpQuy";
            grpQuy.Size = new Size(280, 90);
            grpQuy.Text = "Doanh thu theo quy";
            grpQuy.Controls.Add(lblQuyTitle);
            grpQuy.Controls.Add(nudQuy);
            grpQuy.Controls.Add(lblNamQuyTitle);
            grpQuy.Controls.Add(nudNam2);
            grpQuy.Controls.Add(btnTheoQuy);
            lblQuyTitle.Font = new Font("Segoe UI", 9F);
            lblQuyTitle.Location = new Point(15, 30);
            lblQuyTitle.Name = "lblQuyTitle";
            lblQuyTitle.Text = "Quy:";
            lblQuyTitle.AutoSize = true;
            nudQuy.Location = new Point(15, 52);
            nudQuy.Maximum = new decimal(new int[] { 4, 0, 0, 0 });
            nudQuy.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            nudQuy.Name = "nudQuy";
            nudQuy.Size = new Size(50, 25);
            nudQuy.Value = new decimal(new int[] { 1, 0, 0, 0 });
            lblNamQuyTitle.Font = new Font("Segoe UI", 9F);
            lblNamQuyTitle.Location = new Point(80, 30);
            lblNamQuyTitle.Name = "lblNamQuyTitle";
            lblNamQuyTitle.Text = "Nam:";
            lblNamQuyTitle.AutoSize = true;
            nudNam2.Location = new Point(80, 52);
            nudNam2.Maximum = new decimal(new int[] { 2100, 0, 0, 0 });
            nudNam2.Minimum = new decimal(new int[] { 2000, 0, 0, 0 });
            nudNam2.Name = "nudNam2";
            nudNam2.Size = new Size(70, 25);
            nudNam2.Value = new decimal(new int[] { 2026, 0, 0, 0 });
            btnTheoQuy.BackColor = Color.FromArgb(52, 152, 219);
            btnTheoQuy.FlatStyle = FlatStyle.Flat;
            btnTheoQuy.FlatAppearance.BorderSize = 0;
            btnTheoQuy.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnTheoQuy.ForeColor = Color.White;
            btnTheoQuy.Location = new Point(165, 50);
            btnTheoQuy.Name = "btnTheoQuy";
            btnTheoQuy.Size = new Size(100, 29);
            btnTheoQuy.Text = "XEM";
            btnTheoQuy.UseVisualStyleBackColor = false;
            btnTheoQuy.Click += btnTheoQuy_Click;
            grpNam.Font = new Font("Segoe UI", 9F);
            grpNam.Location = new Point(920, 20);
            grpNam.Name = "grpNam";
            grpNam.Size = new Size(200, 90);
            grpNam.Text = "Doanh thu theo nam";
            grpNam.Controls.Add(lblNamTitle);
            grpNam.Controls.Add(nudNam3);
            grpNam.Controls.Add(btnTheoNam);
            lblNamTitle.Font = new Font("Segoe UI", 9F);
            lblNamTitle.Location = new Point(15, 30);
            lblNamTitle.Name = "lblNamTitle";
            lblNamTitle.Text = "Nam:";
            lblNamTitle.AutoSize = true;
            nudNam3.Location = new Point(15, 52);
            nudNam3.Maximum = new decimal(new int[] { 2100, 0, 0, 0 });
            nudNam3.Minimum = new decimal(new int[] { 2000, 0, 0, 0 });
            nudNam3.Name = "nudNam3";
            nudNam3.Size = new Size(70, 25);
            nudNam3.Value = new decimal(new int[] { 2026, 0, 0, 0 });
            btnTheoNam.BackColor = Color.FromArgb(52, 152, 219);
            btnTheoNam.FlatStyle = FlatStyle.Flat;
            btnTheoNam.FlatAppearance.BorderSize = 0;
            btnTheoNam.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnTheoNam.ForeColor = Color.White;
            btnTheoNam.Location = new Point(95, 50);
            btnTheoNam.Name = "btnTheoNam";
            btnTheoNam.Size = new Size(90, 29);
            btnTheoNam.Text = "XEM";
            btnTheoNam.UseVisualStyleBackColor = false;
            btnTheoNam.Click += btnTheoNam_Click;
            lblKetQua.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblKetQua.Location = new Point(20, 125);
            lblKetQua.Name = "lblKetQua";
            lblKetQua.Text = "Chon 1 khoang thoi gian va bam XEM de xem doanh thu";
            lblKetQua.AutoSize = false;
            lblKetQua.Size = new Size(1100, 55);
            lblKetQua.ForeColor = Color.FromArgb(231, 76, 60);
            grpTop5.Font = new Font("Segoe UI", 9F);
            grpTop5.Location = new Point(20, 195);
            grpTop5.Name = "grpTop5";
            grpTop5.Size = new Size(1100, 230);
            grpTop5.Text = "Top 5 san pham ban chay";
            grpTop5.Controls.Add(lblKieuTop5);
            grpTop5.Controls.Add(cboKieuTop5);
            grpTop5.Controls.Add(dtpTop5);
            grpTop5.Controls.Add(btnTop5);
            grpTop5.Controls.Add(lstTop5);
            lblKieuTop5.Font = new Font("Segoe UI", 9F);
            lblKieuTop5.Location = new Point(15, 32);
            lblKieuTop5.Name = "lblKieuTop5";
            lblKieuTop5.Text = "Thong ke theo:";
            lblKieuTop5.AutoSize = true;
            cboKieuTop5.DropDownStyle = ComboBoxStyle.DropDownList;
            cboKieuTop5.Items.AddRange(new object[] { "Ngay", "Thang", "Nam" });
            cboKieuTop5.Location = new Point(115, 29);
            cboKieuTop5.Name = "cboKieuTop5";
            cboKieuTop5.Size = new Size(100, 25);
            dtpTop5.Format = DateTimePickerFormat.Short;
            dtpTop5.Location = new Point(230, 29);
            dtpTop5.Name = "dtpTop5";
            dtpTop5.Size = new Size(140, 25);
            btnTop5.BackColor = Color.FromArgb(155, 89, 182);
            btnTop5.FlatStyle = FlatStyle.Flat;
            btnTop5.FlatAppearance.BorderSize = 0;
            btnTop5.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnTop5.ForeColor = Color.White;
            btnTop5.Location = new Point(385, 26);
            btnTop5.Name = "btnTop5";
            btnTop5.Size = new Size(110, 30);
            btnTop5.Text = "XEM TOP 5";
            btnTop5.UseVisualStyleBackColor = false;
            btnTop5.Click += btnTop5_Click;
            lstTop5.Font = new Font("Segoe UI", 11F);
            lstTop5.ItemHeight = 20;
            lstTop5.Location = new Point(15, 70);
            lstTop5.Name = "lstTop5";
            lstTop5.Size = new Size(1070, 150);
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(1140, 445);
            Controls.Add(grpNgay);
            Controls.Add(grpThang);
            Controls.Add(grpQuy);
            Controls.Add(grpNam);
            Controls.Add(lblKetQua);
            Controls.Add(grpTop5);
            Name = "FormThongKe";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Thong ke";
            Load += FormThongKe_Load;
            grpNgay.ResumeLayout(false);
            grpNgay.PerformLayout();
            grpThang.ResumeLayout(false);
            grpThang.PerformLayout();
            grpQuy.ResumeLayout(false);
            grpQuy.PerformLayout();
            grpNam.ResumeLayout(false);
            grpNam.PerformLayout();
            grpTop5.ResumeLayout(false);
            grpTop5.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)nudThang).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudNam1).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudQuy).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudNam2).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudNam3).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private GroupBox grpNgay;
        private Label lblChonNgay;
        private DateTimePicker dtpNgay;
        private Button btnTheoNgay;
        private GroupBox grpThang;
        private Label lblThangTitle;
        private NumericUpDown nudThang;
        private Label lblNamThangTitle;
        private NumericUpDown nudNam1;
        private Button btnTheoThang;
        private GroupBox grpQuy;
        private Label lblQuyTitle;
        private NumericUpDown nudQuy;
        private Label lblNamQuyTitle;
        private NumericUpDown nudNam2;
        private Button btnTheoQuy;
        private GroupBox grpNam;
        private Label lblNamTitle;
        private NumericUpDown nudNam3;
        private Button btnTheoNam;
        private Label lblKetQua;
        private GroupBox grpTop5;
        private Label lblKieuTop5;
        private ComboBox cboKieuTop5;
        private DateTimePicker dtpTop5;
        private Button btnTop5;
        private ListBox lstTop5;
    }
}
