namespace QuanLyQuanCafe_WF
{
    partial class FormSanPham
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            lblTimKiem = new Label();
            txtTimKiem = new TextBox();
            btnTimKiem = new Button();
            dgvSanPham = new DataGridView();
            grpThem = new GroupBox();
            lblLoaiSanPham = new Label();
            cboLoaiMoi = new ComboBox();
            lblTenSanPham = new Label();
            txtTenMoi = new TextBox();
            lblGiaSanPham = new Label();
            txtGiaMoi = new TextBox();
            lblThuocTinh = new Label();
            txtThuocTinhMoi = new TextBox();
            lblSoLuongSanPham = new Label();
            txtSoLuongTonMoi = new TextBox();
            btnThemSanPham = new Button();
            grpChinhSua = new GroupBox();
            lblDangChonTitle = new Label();
            lblMaDaChon = new Label();
            lblTenSuaTitle = new Label();
            txtTenSua = new TextBox();
            lblGiaSuaTitle = new Label();
            txtGiaSua = new TextBox();
            btnSua = new Button();
            btnXoa = new Button();
            grpNhapHang = new GroupBox();
            lblSoLuongNhapTitle = new Label();
            txtSoLuongNhap = new TextBox();
            btnNhapHang = new Button();
            grpThem.SuspendLayout();
            grpChinhSua.SuspendLayout();
            grpNhapHang.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvSanPham).BeginInit();
            SuspendLayout();
            lblTimKiem.Font = new Font("Segoe UI", 9F);
            lblTimKiem.Location = new Point(20, 22);
            lblTimKiem.Name = "lblTimKiem";
            lblTimKiem.Text = "Tìm kiếm tên:";
            lblTimKiem.AutoSize = true;
            txtTimKiem.Location = new Point(110, 19);
            txtTimKiem.Name = "txtTimKiem";
            txtTimKiem.Size = new Size(200, 25);
            btnTimKiem.BackColor = Color.FromArgb(52, 152, 219);
            btnTimKiem.FlatStyle = FlatStyle.Flat;
            btnTimKiem.FlatAppearance.BorderSize = 0;
            btnTimKiem.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnTimKiem.ForeColor = Color.White;
            btnTimKiem.Location = new Point(320, 17);
            btnTimKiem.Name = "btnTimKiem";
            btnTimKiem.Size = new Size(100, 29);
            btnTimKiem.Text = "TÌM KIẾM";
            btnTimKiem.UseVisualStyleBackColor = false;
            btnTimKiem.Click += btnTimKiem_Click;
            dgvSanPham.AllowUserToAddRows = false;
            dgvSanPham.AllowUserToDeleteRows = false;
            dgvSanPham.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            dgvSanPham.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvSanPham.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvSanPham.Location = new Point(20, 60);
            dgvSanPham.MultiSelect = false;
            dgvSanPham.Name = "dgvSanPham";
            dgvSanPham.ReadOnly = true;
            dgvSanPham.RowHeadersVisible = false;
            dgvSanPham.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvSanPham.Size = new Size(560, 490);
            dgvSanPham.CellClick += dgvSanPham_CellClick;
            grpThem.Font = new Font("Segoe UI", 9F);
            grpThem.Location = new Point(600, 20);
            grpThem.Name = "grpThem";
            grpThem.Size = new Size(320, 260);
            grpThem.Text = "Thêm sản phẩm mới";
            grpThem.Controls.Add(lblLoaiSanPham);
            grpThem.Controls.Add(cboLoaiMoi);
            grpThem.Controls.Add(lblTenSanPham);
            grpThem.Controls.Add(txtTenMoi);
            grpThem.Controls.Add(lblGiaSanPham);
            grpThem.Controls.Add(txtGiaMoi);
            grpThem.Controls.Add(lblThuocTinh);
            grpThem.Controls.Add(txtThuocTinhMoi);
            grpThem.Controls.Add(lblSoLuongSanPham);
            grpThem.Controls.Add(txtSoLuongTonMoi);
            grpThem.Controls.Add(btnThemSanPham);
            lblLoaiSanPham.Font = new Font("Segoe UI", 9F);
            lblLoaiSanPham.Location = new Point(15, 32);
            lblLoaiSanPham.Name = "lblLoaiSanPham";
            lblLoaiSanPham.Text = "Loại:";
            lblLoaiSanPham.AutoSize = true;
            cboLoaiMoi.DropDownStyle = ComboBoxStyle.DropDownList;
            cboLoaiMoi.Items.AddRange(new object[] { "DoUong", "DoAn", "Combo" });
            cboLoaiMoi.Location = new Point(120, 29);
            cboLoaiMoi.Name = "cboLoaiMoi";
            cboLoaiMoi.Size = new Size(170, 25);
            cboLoaiMoi.SelectedIndexChanged += cboLoaiMoi_SelectedIndexChanged;
            lblTenSanPham.Font = new Font("Segoe UI", 9F);
            lblTenSanPham.Location = new Point(15, 68);
            lblTenSanPham.Name = "lblTenSanPham";
            lblTenSanPham.Text = "Tên:";
            lblTenSanPham.AutoSize = true;
            txtTenMoi.Location = new Point(120, 65);
            txtTenMoi.Name = "txtTenMoi";
            txtTenMoi.Size = new Size(170, 25);
            lblGiaSanPham.Font = new Font("Segoe UI", 9F);
            lblGiaSanPham.Location = new Point(15, 104);
            lblGiaSanPham.Name = "lblGiaSanPham";
            lblGiaSanPham.Text = "Giá:";
            lblGiaSanPham.AutoSize = true;
            txtGiaMoi.Location = new Point(120, 101);
            txtGiaMoi.Name = "txtGiaMoi";
            txtGiaMoi.Size = new Size(170, 25);
            lblThuocTinh.Font = new Font("Segoe UI", 9F);
            lblThuocTinh.Location = new Point(15, 140);
            lblThuocTinh.Name = "lblThuocTinh";
            lblThuocTinh.Text = "Thuộc tính riêng:";
            lblThuocTinh.AutoSize = true;
            txtThuocTinhMoi.Location = new Point(120, 137);
            txtThuocTinhMoi.Name = "txtThuocTinhMoi";
            txtThuocTinhMoi.Size = new Size(170, 25);
            lblSoLuongSanPham.Font = new Font("Segoe UI", 9F);
            lblSoLuongSanPham.Location = new Point(15, 176);
            lblSoLuongSanPham.Name = "lblSoLuongSanPham";
            lblSoLuongSanPham.Text = "Số lượng tồn:";
            lblSoLuongSanPham.AutoSize = true;
            txtSoLuongTonMoi.Location = new Point(120, 173);
            txtSoLuongTonMoi.Name = "txtSoLuongTonMoi";
            txtSoLuongTonMoi.Size = new Size(170, 25);
            btnThemSanPham.BackColor = Color.FromArgb(46, 204, 113);
            btnThemSanPham.FlatStyle = FlatStyle.Flat;
            btnThemSanPham.FlatAppearance.BorderSize = 0;
            btnThemSanPham.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnThemSanPham.ForeColor = Color.White;
            btnThemSanPham.Location = new Point(15, 210);
            btnThemSanPham.Name = "btnThemSanPham";
            btnThemSanPham.Size = new Size(275, 33);
            btnThemSanPham.Text = "THÊM SẢN PHẨM";
            btnThemSanPham.UseVisualStyleBackColor = false;
            btnThemSanPham.Click += btnThemSanPham_Click;
            grpChinhSua.Font = new Font("Segoe UI", 9F);
            grpChinhSua.Location = new Point(600, 285);
            grpChinhSua.Name = "grpChinhSua";
            grpChinhSua.Size = new Size(320, 190);
            grpChinhSua.Text = "Sửa / xóa sản phẩm đã chọn trong bảng";
            grpChinhSua.Controls.Add(lblDangChonTitle);
            grpChinhSua.Controls.Add(lblMaDaChon);
            grpChinhSua.Controls.Add(lblTenSuaTitle);
            grpChinhSua.Controls.Add(txtTenSua);
            grpChinhSua.Controls.Add(lblGiaSuaTitle);
            grpChinhSua.Controls.Add(txtGiaSua);
            grpChinhSua.Controls.Add(btnSua);
            grpChinhSua.Controls.Add(btnXoa);
            lblDangChonTitle.Font = new Font("Segoe UI", 9F);
            lblDangChonTitle.Location = new Point(15, 32);
            lblDangChonTitle.Name = "lblDangChonTitle";
            lblDangChonTitle.Text = "Đang chọn:";
            lblDangChonTitle.AutoSize = true;
            lblMaDaChon.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblMaDaChon.Location = new Point(110, 32);
            lblMaDaChon.Name = "lblMaDaChon";
            lblMaDaChon.Text = "chưa chọn";
            lblMaDaChon.AutoSize = true;
            lblMaDaChon.ForeColor = Color.FromArgb(44, 62, 80);
            lblTenSuaTitle.Font = new Font("Segoe UI", 9F);
            lblTenSuaTitle.Location = new Point(15, 68);
            lblTenSuaTitle.Name = "lblTenSuaTitle";
            lblTenSuaTitle.Text = "Tên:";
            lblTenSuaTitle.AutoSize = true;
            txtTenSua.Location = new Point(120, 65);
            txtTenSua.Name = "txtTenSua";
            txtTenSua.Size = new Size(170, 25);
            lblGiaSuaTitle.Font = new Font("Segoe UI", 9F);
            lblGiaSuaTitle.Location = new Point(15, 104);
            lblGiaSuaTitle.Name = "lblGiaSuaTitle";
            lblGiaSuaTitle.Text = "Giá:";
            lblGiaSuaTitle.AutoSize = true;
            txtGiaSua.Location = new Point(120, 101);
            txtGiaSua.Name = "txtGiaSua";
            txtGiaSua.Size = new Size(170, 25);
            btnSua.BackColor = Color.FromArgb(52, 152, 219);
            btnSua.FlatStyle = FlatStyle.Flat;
            btnSua.FlatAppearance.BorderSize = 0;
            btnSua.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnSua.ForeColor = Color.White;
            btnSua.Location = new Point(15, 138);
            btnSua.Name = "btnSua";
            btnSua.Size = new Size(130, 33);
            btnSua.Text = "SỬA";
            btnSua.UseVisualStyleBackColor = false;
            btnSua.Click += btnSua_Click;
            btnXoa.BackColor = Color.FromArgb(231, 76, 60);
            btnXoa.FlatStyle = FlatStyle.Flat;
            btnXoa.FlatAppearance.BorderSize = 0;
            btnXoa.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnXoa.ForeColor = Color.White;
            btnXoa.Location = new Point(160, 138);
            btnXoa.Name = "btnXoa";
            btnXoa.Size = new Size(130, 33);
            btnXoa.Text = "XÓA";
            btnXoa.UseVisualStyleBackColor = false;
            btnXoa.Click += btnXoa_Click;
            grpNhapHang.Font = new Font("Segoe UI", 9F);
            grpNhapHang.Location = new Point(600, 485);
            grpNhapHang.Name = "grpNhapHang";
            grpNhapHang.Size = new Size(320, 65);
            grpNhapHang.Text = "Nhập thêm hàng cho sp đã chọn";
            grpNhapHang.Controls.Add(lblSoLuongNhapTitle);
            grpNhapHang.Controls.Add(txtSoLuongNhap);
            grpNhapHang.Controls.Add(btnNhapHang);
            lblSoLuongNhapTitle.Font = new Font("Segoe UI", 9F);
            lblSoLuongNhapTitle.Location = new Point(15, 30);
            lblSoLuongNhapTitle.Name = "lblSoLuongNhapTitle";
            lblSoLuongNhapTitle.Text = "Số lượng:";
            lblSoLuongNhapTitle.AutoSize = true;
            txtSoLuongNhap.Location = new Point(105, 27);
            txtSoLuongNhap.Name = "txtSoLuongNhap";
            txtSoLuongNhap.Size = new Size(80, 25);
            btnNhapHang.BackColor = Color.FromArgb(46, 204, 113);
            btnNhapHang.FlatStyle = FlatStyle.Flat;
            btnNhapHang.FlatAppearance.BorderSize = 0;
            btnNhapHang.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnNhapHang.ForeColor = Color.White;
            btnNhapHang.Location = new Point(195, 25);
            btnNhapHang.Name = "btnNhapHang";
            btnNhapHang.Size = new Size(110, 29);
            btnNhapHang.Text = "NHẬP HÀNG";
            btnNhapHang.UseVisualStyleBackColor = false;
            btnNhapHang.Click += btnNhapHang_Click;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(950, 570);
            Controls.Add(lblTimKiem);
            Controls.Add(txtTimKiem);
            Controls.Add(btnTimKiem);
            Controls.Add(dgvSanPham);
            Controls.Add(grpThem);
            Controls.Add(grpChinhSua);
            Controls.Add(grpNhapHang);
            MinimumSize = new Size(850, 500);
            Name = "FormSanPham";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Quản lý sản phẩm";
            Load += FormSanPham_Load;
            grpThem.ResumeLayout(false);
            grpThem.PerformLayout();
            grpChinhSua.ResumeLayout(false);
            grpChinhSua.PerformLayout();
            grpNhapHang.ResumeLayout(false);
            grpNhapHang.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvSanPham).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private Label lblTimKiem;
        private TextBox txtTimKiem;
        private Button btnTimKiem;
        private DataGridView dgvSanPham;
        private GroupBox grpThem;
        private Label lblLoaiSanPham;
        private ComboBox cboLoaiMoi;
        private Label lblTenSanPham;
        private TextBox txtTenMoi;
        private Label lblGiaSanPham;
        private TextBox txtGiaMoi;
        private Label lblThuocTinh;
        private TextBox txtThuocTinhMoi;
        private Label lblSoLuongSanPham;
        private TextBox txtSoLuongTonMoi;
        private Button btnThemSanPham;
        private GroupBox grpChinhSua;
        private Label lblDangChonTitle;
        private Label lblMaDaChon;
        private Label lblTenSuaTitle;
        private TextBox txtTenSua;
        private Label lblGiaSuaTitle;
        private TextBox txtGiaSua;
        private Button btnSua;
        private Button btnXoa;
        private GroupBox grpNhapHang;
        private Label lblSoLuongNhapTitle;
        private TextBox txtSoLuongNhap;
        private Button btnNhapHang;
    }
}
